### ISSUE TITLE
Q integration: new site (not WP or Drupal) has loading icons for Stack, etc

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Agent-Client#12]

**Comment by aschmoe** [comment]
@jlyon this was an issue with the API having a default value for application, which is now a value reserved for "drupal" + "wordpress"

@gregelin any sites you created that are experiencing this issue will continue to do so.  If you give us their information + the account they can be fixed, but otherwise new ones must be created.

**Comment by gregelin** [comment]
@aschmoe Thanks. Will note. Is it possible to delete sites via UI?

**Comment by jlyon** [comment]
> . Is it possible to delete sites via UI?

@gregelin Created an issue for this https://github.com/GovReady/GovReady-Agent-Client/issues/16

---

I pushed a PR to fix this https://github.com/GovReady/govready-q-ssp-module/pull/1
